{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "taiga.fullname" . }}
  labels: {{- include "taiga.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "taiga.tplValue" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        - path: /
          backend:
            serviceName: "{{ template "taiga.fullname" . }}-front"
            servicePort: taiga-front
        - path: /api
          backend:
            serviceName: "{{ template "taiga.fullname" . }}-back"
            servicePort: taiga-back
        - path: /admin
          backend:
            serviceName: "{{ template "taiga.fullname" . }}-back"
            servicePort: taiga-back
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
        - path: {{ default "/" .path }}
          backend:
            serviceName: "{{ template "taiga.fullname" $ }}-back"
            servicePort: taiga-back
        - path: /events
          backend:
            serviceName: "{{ template "taiga.fullname" . }}-events"
            servicePort: taiga-events
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls .Values.ingress.hosts }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- toYaml .Values.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
