{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "taiga.fullname" . }}
  labels: {{- include "taiga.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
    {{- if .Values.ingress.certManager }}
    kubernetes.io/tls-acme: "true"
    {{- end }}
    {{- if .Values.ingress.annotations }}
    {{- include "taiga.tplValue" (dict "value" .Values.ingress.annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  rules:
    {{- if .Values.ingress.hostname }}
    - host: {{ .Values.ingress.hostname }}
      http:
        paths:
        {{- if .Values.gateway.enabled }}
        - path: /
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-back"
              port:
                name: taiga-gateway
          pathType: ImplementationSpecific
       {{- else }}
        - path: /
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-front"
              port:
                name: taiga-front
          pathType: ImplementationSpecific
        - path: /api
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-back"
              port:
                name: taiga-back
          pathType: ImplementationSpecific
        - path: /admin
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-back"
              port:
                name: taiga-back
          pathType: ImplementationSpecific
        - path: /events
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-events"
              port:
                name: taiga-events
          pathType: ImplementationSpecific
        - path: /media
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-protected"
              port:
                name: taiga-protected
          pathType: ImplementationSpecific
        {{- end }}
    {{- end }}
    {{- range .Values.ingress.extraHosts }}
    - host: {{ .name }}
      http:
        paths:
        {{- if .Values.gateway.enabled }}
        - path: {{ default "/" .path }}
          backend:
            service:
              name: "{{ template "taiga.fullname" $ }}-back"
              port:
                name: taiga-gateway
          pathType: ImplementationSpecific
        {{- else }}
        - path: {{ default "/" .path }}
          backend:
            service:
              name: "{{ template "taiga.fullname" $ }}-front"
              port:
                name: taiga-back
          pathType: ImplementationSpecific
        - path: /api
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-back"
              port:
                name: taiga-back
          pathType: ImplementationSpecific
        - path: /admin
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-back"
              port:
                name: taiga-back
          pathType: ImplementationSpecific
        - path: /events
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-events"
              port:
                name: taiga-events
          pathType: ImplementationSpecific
        - path: /media
          backend:
            service:
              name: "{{ template "taiga.fullname" . }}-protected"
              port:
                name: taiga-protected
          pathType: ImplementationSpecific
        {{- end }}
    {{- end }}
  {{- if or .Values.ingress.tls .Values.ingress.extraTls .Values.ingress.hosts }}
  tls:
    {{- if .Values.ingress.tls }}
    - hosts:
        - {{ .Values.ingress.hostname }}
      secretName: {{ printf "%s-tls" .Values.ingress.hostname }}
    {{- end }}
    {{- if .Values.ingress.extraTls }}
    {{- toYaml .Values.ingress.extraTls | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
